# Generated by Django 5.1.7 on 2025-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_create_guest_users_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
