# Generated by Django 5.1.7 on 2025-03-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_remove_offerdetails_offer_id_offer_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
