# Generated by Django 5.1.7 on 2025-03-30 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_alter_offerdetail_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
    ]
