# Generated by Django 5.1.7 on 2025-04-02 13:46

import django.core.validators
import offers_app.api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0007_alter_offerdetail_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='offer-imgs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), offers_app.api.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
