# Generated by Django 5.1.7 on 2025-04-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_alter_review_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
