# Generated by Django 5.1.7 on 2025-04-04 01:10

import django.core.validators
import profiles_app.api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='profile-imgs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), profiles_app.api.utils.validate_file_size])),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], editable=False, max_length=20)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('tel', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
