# Generated by Django 5.1.7 on 2025-03-20 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessUserProfile',
            new_name='BusinessProfile',
        ),
        migrations.RenameModel(
            old_name='CustomerUserProfile',
            new_name='CustomerProfile',
        ),
    ]
