# Generated by Django 5.1.7 on 2025-03-20 15:04

import django.core.validators
import profiles_app.api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_rename_businessuserprofile_businessprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), profiles_app.api.utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), profiles_app.api.utils.validate_file_size]),
        ),
    ]
