# Generated by Django 5.1.7 on 2025-03-20 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0003_alter_businessprofile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='last_name',
        ),
    ]
