# Generated by Django 5.1.7 on 2025-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0004_remove_businessprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], editable=False, max_length=20),
        ),
    ]
