# Generated by Django 5.1.7 on 2025-03-27 23:33

import django.core.validators
import profiles_app.api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0006_alter_userprofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='profile-imgs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), profiles_app.api.utils.validate_file_size]),
        ),
    ]
