# Generated by Django 5.1.7 on 2025-03-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0007_alter_businessprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], max_length=20),
        ),
    ]
